name: mi_negocio_backend

version: 0.0.1+1
environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  dart_frog: ^1.0.0
  uuid: ^4.0.0
  dart_jsonwebtoken: ^2.7.0

dev_dependencies:
  dart_frog_cli: ^1.2.5